title:            AnrainerKot
description:      "AnrainerKot"
logo:             omikron.png
disqus_shortname: hmfaysal
default_bg:       default_bg1.jpg
search:           true
share:            true
readtime:         true
wpm:				      200
triangleheader:		true
animated_fins:	  true
fin_color:        "255,255,255"
url:       		   

owner:
  name:           AnrainerKot
  avatar:         hmfaysal.jpg
  twitter:        anrainerkot

links:
  - title: Home
    url: /
    external: false
    icon: home
timezone:    Europe/Vienna
future:      true
highlighter: pygments
markdown:    kramdown
paginate:    6
paginate_path: "page:num"

permalink:   /:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

prose:
  rooturl: '_posts'
  siteurl: 'http://anrainerkot.wien/'
  relativeLinks: 'http://anrainerkot.wien/links.jsonp'
  media: 'images'
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
      - name: "type"
        field:
          element: "select"
          label: "Select Post Type"
          placeholder: "Choose your type"
          options:
            - name: "Standard"
              value: 
            - name: "Quote"
              value: quote
            - name: "Status"
              value: status
            - name: "Photo"
              value: photo
            - name: "Video"
              value: video
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "An Awesome Headline!"
      - name: "description"
        field:
          element: "text"
          label: "Description"
          placeholder: "Enter Post Description"
      - name: "headline"
        field:
          element: "text"
          label: "beadline"
          placeholder: "Enter Post Headline"
      - name: "modified"
        field:
          element: "text"
          label: "Has this page been modified?"
          placeholder: "YYYY-MM-DD"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add categories"
          placeholder: "Choose categories"
          value: personal
          options:
            - name: "Personal"
              value: personal
            - name: "Web-Development"
              value: webdevelopment
            - name: "Interesting"
              value: interesting
            - name: "Status"
              value: status
            - name: "Quotes"
              value: quotes
          alterable: true
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          placeholder: "Enter tags, separated by spaces"
      - name: "imagefeature"
        field:
          element: "text"
          label: "Featured Image"
          placeholder: "somefile.jpg"
      - name: "imagecredit"
        field:
          element: "text"
          label: "Image Credit"
          placeholder: "some guy"
      - name: "imagecreditlink"
        field:
          element: "text"
          label: "Credit link for the image"
          placeholder: "http://somewebsite.com"
      - name: "video"
        field:
          element: "text"
          label: "Insert Youtube Link"
          placeholder: "http://youtube.com/somevideo"
      - name: "mathjax"
        field:
          element: "checkbox"
          label: "MathJax"
          value: false
      - name: "featured"
        field:
          element: "checkbox"
          label: "Featured?"
          value: false
      - name: "comments"
        field:
          element: "checkbox"
          label: "Comments"
          value: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
